server:
  servlet:
#    ???????
    context-path: /bankOnline

#    ??????(??????????????,??????????)
spring:
  application:
    name: /bankOnline

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bankOnline?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=UTF-8
    username: root
    password: root


  thymeleaf:
    cache: false


mybatis-plus:
  mapper-locations: classpath:com/hxzyyn/mapper/*.xml
  type-aliases-package: com.hxzyyn.entity





